import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Bot, Sparkles } from 'lucide-react';

interface BriefingViewProps {
  content: string;
}

export const BriefingView: React.FC<BriefingViewProps> = ({ content }) => {
  return (
    <div className="glass-panel rounded-xl p-6 md:p-8 min-h-[400px]">
      <div className="flex items-center gap-3 mb-6 pb-4 border-b border-white/5">
        <div className="relative">
          <div className="absolute inset-0 bg-blue-500/20 blur-md rounded-full"></div>
          <Bot className="w-6 h-6 text-blue-400 relative z-10" />
        </div>
        <div>
          <h2 className="text-lg font-display font-semibold text-white flex items-center gap-2">
            Intelligence Briefing
            <Sparkles className="w-3 h-3 text-india-saffron animate-pulse" />
          </h2>
          <p className="text-xs text-slate-400">Generated by Gemini 2.5 Flash</p>
        </div>
      </div>
      
      <div className="markdown-content">
        <ReactMarkdown>{content}</ReactMarkdown>
      </div>
    </div>
  );
};